services:
  - type: web
    name: dataset-website
    runtime: python
    buildCommand: pip install -r requirements.txt && pip install gunicorn
    startCommand: gunicorn wsgi:app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
      - key: FLASK_ENV
        value: production
